name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Also allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r .github/scripts/project_cards/requirements.txt

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ github.token }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: python .github/scripts/project_cards/project_cards.py

      - name: Save generated SVGs temporarily
        run: |
          mkdir -p "$RUNNER_TEMP/tmp_svgs"
          cp readme-*.svg "$RUNNER_TEMP/tmp_svgs/"

      - name: Create orphan branch and commit SVGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan generated-repo-images
          git reset --hard
          git clean -fdx
          cp "$RUNNER_TEMP/tmp_svgs/"*.svg ./
          git add readme-*.svg
          git commit -m "Auto-update project cards"

      - name: Push orphan branch
        run: git push --force origin generated-repo-images
